name: your_app
description: A Flutter application using clean architecture
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  get: ^4.6.6
  hive: ^2.2.3
  dio: ^5.4.3
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  audioplayers: ^6.5.1
  get_it: ^7.2.0
  logger: ^1.1.0
  firebase_messaging: 15.2.10
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/balance.png
    - assets/images/icons/
    - assets/audio/
